version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: savannah_assess:v1
    env_file:
      - .env
    environment:
      DB_HOST: postgres_db
      PORT: 8888  
    ports:
      - "8888:8888"
    depends_on:
      - postgres_db
    restart: always
    command: sh -c "/app/migrate.sh && /app/entrypoint.sh"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  postgres_db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

volumes:
  postgres_data:
