version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: savannah_assess:v1
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    restart: always
    command: ["/app/start.sh"]

  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Comment out in production:
    ports:
      - "5433:5432"

volumes:
  postgres_data:
