apiVersion: v1
kind: ConfigMap
metadata:
  name: savannah-assess-config
  namespace: savannah-assess
data:
  DB_NAME: "savannah_assess"
  DB_USER: "postgres"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  PYTHONDONTWRITEBYTECODE: "1"
  PYTHONUNBUFFERED: "1"
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  DJANGO_SUPERUSER_USERNAME: "admin"
  DJANGO_SUPERUSER_EMAIL: "admin@savannah.local"
