apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
  namespace: savannah-assess
  labels:
    app: django-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      initContainers:
        - name: migrate
          image: otizaaa/savannah_assess:v2
          command: ["/app/migrate.sh"]
          envFrom:
            - configMapRef:
                name: savannah-assess-config
            - secretRef:
                name: savannah-assess-secret
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: savannah-assess-secret
                  key: DB_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: savannah-assess-secret
                  key: DJANGO_SECRET_KEY
      containers:
        - name: django-app
          image: otizaaa/savannah_assess:v2
          ports:
            - containerPort: 8888
          envFrom:
            - configMapRef:
                name: savannah-assess-config
            - secretRef:
                name: savannah-assess-secret
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: savannah-assess-secret
                  key: DB_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: savannah-assess-secret
                  key: DJANGO_SECRET_KEY
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
